swagger: "2.0"
info:
  description: "This is an example for DesarrolloJavaYYo"
  version: "1.0.0"
  title: "Swagger Libbrary"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "DesarrolloJavaYYo@blogger.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v1"
tags:
- name: "book"
  description: "Everything about our Books"
  externalDocs:
    description: "Find out more"
    url: "http://DesarrolloJavaYYo.blogspot.com"
schemes:
- "https"
paths:
  /book:
    get:
      tags:
      - "book"
      summary: "List all books"
      description: ""
      operationId: "findAll"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Book"
        500:
          description: "Internal Server Error"
  /book/{bookId}:
    get:
      tags:
      - "book"
      summary: "Find a book"
      description: ""
      operationId: "findById"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "bookId"
        in: "path"
        description: "ID of the book that you want"
        required: true
        type: "integer"
        minimum: 1.0
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Book"
        500:
          description: "Internal Server Error"
definitions:
  Book:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      author:
        type: "string"
      creationDate:
        type: "string"
        format: "date-time"
      editDate:
        type: "string"
        format: "date-time"
      creationUser:
        type: "integer"
        format: "int64"
      editUser:
        type: "integer"
        format: "int64"
    xml:
      name: "Book"
