openapi: 3.0.1
info:
  title: activemqExample_v1_book_api
  description: API Definition of activemqExample_v1_book_api
  version: 1.0.0
servers:
- url: http://localhost:8290/book
paths:
  /:
    get:
      responses:
        default:
          description: Default response
  /mock/:
    get:
      responses:
        default:
          description: Default response
  /mock/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
